"use strict";

export const jobitems = [
	{
		job_id: "RB1234",
		item_id: "9999",
		product: "Pick-n-Mix Ball",
		description: "hello",
		glass: "Denim ~ Diamond",
		metal: "Brass",
		flex: "Havana Gold ~ Twist",
		bulb: "25W Incandescent Golfball E14 SES",
		qty_req: 5,
		qty_hot: 3,
		qty_cold: 3,
		qty_assem: 3,
		qty_packed: 3,
		notes: "hello"
	},
	{
		job_id: "RB1234",
		item_id: "hi",
		product: "hello",
		description: "hello",
		glass: "hello",
		metal: "hello",
		flex: "hello",
		bulb: "hello",
		qty_req: 2,
		qty_hot: 2,
		qty_cold: 2,
		qty_assem: 2,
		qty_packed: 2,
		notes: "hello"
	},
	{
		job_id: "RB2845",
		item_id: "1234",
		product: "Pick-n-Mix Ball",
		description: "hello",
		glass: "Denim ~ Diamond",
		metal: "Brass",
		flex: "Havana Gold ~ Twist",
		bulb: "25W Incandescent Golfball E14 SES",
		qty_req: 5,
		qty_hot: 3,
		qty_cold: 3,
		qty_assem: 3,
		qty_packed: 3,
		notes: "hello"
	},
	{
		job_id: "RB2845",
		item_id: "4444",
		product: "hello",
		description: "hello",
		glass: "hello",
		metal: "hello",
		flex: "hello",
		bulb: "hello",
		qty_req: 2,
		qty_hot: 2,
		qty_cold: 2,
		qty_assem: 2,
		qty_packed: 2,
		notes: "hello"
	},
	{
		job_id: "RB2325",
		item_id: "3333",
		product: "Pick-n-Mix Ball",
		description: "hello",
		glass: "Denim ~ Diamond",
		metal: "Brass",
		flex: "Havana Gold ~ Twist",
		bulb: "25W Incandescent Golfball E14 SES",
		qty_req: 5,
		qty_hot: 3,
		qty_cold: 3,
		qty_assem: 3,
		qty_packed: 3,
		notes: "hello"
	},
	{
		job_id: "RB2325",
		item_id: "2222",
		product: "hello",
		description: "hello",
		glass: "hello",
		metal: "hello",
		flex: "hello",
		bulb: "hello",
		qty_req: 2,
		qty_hot: 2,
		qty_cold: 2,
		qty_assem: 2,
		qty_packed: 2,
		notes: "hello"
	}
];

export const jobs = [
	{
		"job_id": "RB1234",
		"details" : {
			job_id: "RB1234",
			client: "Acme Incorporated Ltd",
			project: "Showroom",
			client_ref: "PO-123456-ABC",
			notes: "happy go lucky",
			job_status: "Confirmed",
			order_type: "Bespoke",
			last_update: "2015-01-12",
			parts_status: "waiting",
			parts_notes: "when they coming???",
			shipping_date: "2015-12-30",
			delivery_details: "53 sussex rd",
			payment: ""
		},
		"items": jobitems.filter(item => item.job_id === "RB1234")
	},
	{
		"job_id": "RB2325",
		"details" : {
			job_id: "RB2325",
			client: "Acme Incorporated Ltd",
			project: "Showroom",
			client_ref: "PO-123456-ABC",
			notes: "happy go lucky",
			job_status: "Confirmed",
			order_type: "Bespoke",
			last_update: "2015-01-12",
			parts_status: "waiting",
			parts_notes: "when they coming???",
			shipping_date: "2015-12-30",
			delivery_details: "53 sussex rd",
			payment: ""
		},
		"items": jobitems.filter(item => item.job_id === "RB2325")
	},
	{
		"job_id": "RB2845",
		"details" : {
			job_id: "RB2845",
			client: "Acme Incorporated Ltd",
			project: "Showroom",
			client_ref: "PO-123456-ABC",
			notes: "happy go lucky",
			job_status: "Confirmed",
			order_type: "Bespoke",
			last_update: "2015-01-12",
			parts_status: "waiting",
			parts_notes: "when they coming???",
			shipping_date: "2015-12-30",
			delivery_details: "53 sussex rd",
			payment: ""
		},
		"items": jobitems.filter(item => item.job_id === "RB2845")
	}
];

export const selections = {
	job_status: ["TBC", "Non-Starter", "Confirmed", "Packaged", "Dispatched", "Done"],
	order_type: ["Standard", "Bespoke", "RB Parts", "Outsourced", "Loan or Press"],
	parts_status: ["", "Started", "Done"],
	payment: ["", "Awaiting Payment", "Deposit", "Paid Card", "Paid BACS", "Paid Other", "Non-Starter"],

	glass: [
	"Amber ~ Bubble", "Amber ~ Diamond", "Amber ~ Optic", "Amber ~ Plain",
	"Aubergine ~ Bubble", "Aubergine ~ Diamond", "Aubergine ~ Optic", "Aubergine ~ Plain",
	"Black ~ Bubble", "Black ~ Diamond", "Black ~ Optic", "Black ~ Plain",
	"Bronze ~ Bubble", "Bronze ~ Diamond", "Bronze ~ Optic", "Bronze ~ Plain",
	"Cherry ~ Bubble", "Cherry ~ Diamond", "Cherry ~ Optic", "Cherry ~ Plain",
	"Clear ~ Bubble", "Clear ~ Diamond", "Clear ~ Optic", "Clear ~ Plain",
	"Copper Blue ~ Bubble", "Copper Blue ~ Diamond", "Copper Blue ~ Optic", "Copper Blue ~ Plain",
	"Denim ~ Bubble", "Denim ~ Diamond", "Denim ~ Optic", "Denim ~ Plain",
	"Eel ~ Bubble", "Eel ~ Diamond", "Eel ~ Optic", "Eel ~ Plain",
	"Forest Green ~ Bubble", "Forest Green ~ Diamond", "Forest Green ~ Optic", "Forest Green ~ Plain",
	"Grey ~ Bubble", "Grey ~ Diamond", "Grey ~ Optic", "Grey ~ Plain",
	"Jade ~ Bubble", "Jade ~ Diamond", "Jade ~ Optic", "Jade ~ Plain",
	"Ochre ~ Bubble", "Ochre ~ Diamond", "Ochre ~ Optic", "Ochre ~ Plain",
	"Peach ~ Bubble", "Peach ~ Diamond", "Peach ~ Optic", "Peach ~ Plain",
	"Purple ~ Bubble", "Purple ~ Diamond", "Purple ~ Optic", "Purple ~ Plain",
	"Ruby ~ Bubble", "Ruby ~ Diamond", "Ruby ~ Optic", "Ruby ~ Plain",
	"Sargasso ~ Bubble", "Sargasso ~ Diamond", "Sargasso ~ Optic", "Sargasso ~ Plain",
	"Steel ~ Bubble", "Steel ~ Diamond", "Steel ~ Optic", "Steel ~ Plain",
	"Tea ~ Bubble", "Tea ~ Diamond", "Tea ~ Optic", "Tea ~ Plain"
	],
	metal: [
	"Antique Brass",
	"Black",
	"Brass - Polished",
	"Brass - Matte",
	"Brass - Raw",
	"Bronze - Matte",
	"Bronze - Polished",
	"Copper",
	"Nickel",
	"Nickel - Brushed",
	"White",
	"Zinc"
		],
	flex: [
	"B&W Herringbone ~ 3-Core Round",
		"B&W Herringbone ~ 3-Core Twisted",
		"Black ~ 3-Core Round",
		"Black ~ 3-Core Twisted",
		"Bright Blue ~ 3-Core Round",
		"Bright Blue ~ 3-Core Twisted",
		"Brown ~ 3-Core Round",
		"Brown ~ 3-Core Twisted",
		"Burgundy ~ 3-Core Round",
		"Burgundy ~ 3-Core Twisted",
		"Copper Metal Braid ~ 3-Core Round",
		"Elephant Grey ~ 3-Core Round",
		"Elephant Grey ~ 3-Core Twisted",
		"Fuschia ~ 3-Core Round",
		"Fuschia ~ 3-Core Twisted",
		"Havana Gold ~ 3-Core Round",
		"Havana Gold ~ 3-Core Twisted",
		"Khaki ~ 3-Core Round",
		"Khaki ~ 3-Core Twisted",
		"Light Grey ~ 3-Core Round",
		"Light Grey ~ 3-Core Twisted",
		"Light Purple ~ 3-Core Round",
		"Light Purple ~ 3-Core Twisted",
		"Navy Blue ~ 3-Core Round",
		"Navy Blue ~ 3-Core Twisted",
		"Neon Green ~ 3-Core Round",
		"Neon Green ~ 3-Core Twisted",
		"Neon Yellow ~ 3-Core Round",
		"Neon Yellow ~ 3-Core Twisted",
		"Nickel Metal Braid ~ 3-Core Round",
		"Old Gold ~ 3-Core Round",
		"Old Gold ~ 3-Core Twisted",
		"Orange ~ 3-Core Round",
		"Orange ~ 3-Core Twisted",
		"Pea Green ~ 3-Core Round",
		"Pea Green ~ 3-Core Twisted",
		"Poppy Red ~ 3-Core Round",
		"Poppy Red ~ 3-Core Twisted",
		"Purple ~ 3-Core Round",
		"Purple ~ 3-Core Twisted",
		"Racing Green ~ 3-Core Round",
		"Racing Green ~ 3-Core Twisted",
		"Red & W Herringbone ~ 3-Core Round",
		"Red & W Herringbone ~ 3-Core Twisted",
		"Rose ~ 3-Core Round",
		"Rose ~ 3-Core Twisted",
		"Royal Blue ~ 3-Core Round",
		"Royal Blue ~ 3-Core Twisted",
		"Satinwood Gold ~ 3-Core Round",
		"Satinwood Gold ~ 3-Core Twisted",
		"Silver & White Herringbone ~ 3-Core Round",
		"Silver ~ 3-Core Round",
		"Silver ~ 3-Core Twisted",
		"Tisane ~ 3-Core Round",
		"Tisane ~ 3-Core Twisted",
		"White ~ 3-Core Round",
		"White ~ 3-Core Twisted",
		"Yellow ~ 3-Core Round",
		"Yellow ~ 3-Core Twisted"
		],
	bulb: [
	"Incandescent Golfball ~ E14 (SES)",
	"Incandescent Candle ~ E14 (SES)",
	"LED Candle ~ E14 (SES)",
	"LED Golfball ~ E14 (SES)",
	"Halogen Golfball ~ E27 (ES)",
	"LED Golfball ~ E27 (ES)",
	"Incandescent Squirrel ~ E27 (ES)",
	"Incandescent Picture ~ E14 (SES)",
	"Incandescent Golfball ~ E27 (ES)",
	"Incandescent Lantern ~ E27 (ES)",
	"Compact Fluorescent ~ E14 (SES)"
	],
	product: [
	"Black Nouveau Bell",
	"Black Nouveau Open",
	"Bubble Light",
	"Empire Short",
	"Empire Tall",
	"Flora Pendant Large",
	"Flora Pendant Small",
	"Heal\"s Tassel",
	"Heal\"s Vintage",
	"Lantern Light",
	"Open Optic",
	"Opulent Optic",
	"Opulent Optic w/ burgundy fringe",
	"Opulent Optic w/ gold fringe",
	"Opulent Optic w/ grey fringe",
	"Pick-n-Mix Ball",
	"Pick-n-Mix Bowl",
	"Pick-n-Mix Cylinder",
	"Pick-n-Mix Large Ball",
	"Pick-n-Mix Large Bowl",
	"Pick-n-Mix Large Cylinder",
	"Pick-n-Mix Large Pot",
	"Pick-n-Mix Pot",
	"Retro Light",
	"Spindle Pendant 3-Bubble",
	"Spindle Pendant 4-Bubble",
	"Spindle Shade",
	"Standing Pendant",
	"Tassel Light",
	"Tiered Light",
	"Vintage Light",
	"1-drop Standard Lilleys",
	"1-Drop Empire",
	"3-Drop D265mm",
	"4-Drop D265mm",
	"Bespoke multi-drop",
	"B&W Herringbone ~ 3-Core Round",
	"B&W Herringbone ~ 3-Core Twisted",
	"Black ~ 3-Core Round",
	"Black ~ 3-Core Twisted",
	"Bright Blue ~ 3-Core Round",
	"Bright Blue ~ 3-Core Twisted",
	"Brown ~ 3-Core Round",
	"Brown ~ 3-Core Twisted",
	"Burgundy ~ 3-Core Round",
	"Burgundy ~ 3-Core Twisted",
	"Copper Metal Braid ~ 3-Core Round",
	"Elephant Grey ~ 3-Core Round",
	"Elephant Grey ~ 3-Core Twisted",
	"Fuschia ~ 3-Core Round",
	"Fuschia ~ 3-Core Twisted",
	"Havana Gold ~ 3-Core Round",
	"Havana Gold ~ 3-Core Twisted",
	"Khaki ~ 3-Core Round",
	"Khaki ~ 3-Core Twisted",
	"Light Grey ~ 3-Core Round",
	"Light Grey ~ 3-Core Twisted",
	"Light Purple ~ 3-Core Round",
	"Light Purple ~ 3-Core Twisted",
	"Navy Blue ~ 3-Core Round",
	"Navy Blue ~ 3-Core Twisted",
	"Neon Green ~ 3-Core Round",
	"Neon Green ~ 3-Core Twisted",
	"Neon Yellow ~ 3-Core Round",
	"Neon Yellow ~ 3-Core Twisted",
	"Nickel Metal Braid ~ 3-Core Round",
	"Old Gold ~ 3-Core Round",
	"Old Gold ~ 3-Core Twisted",
	"Orange ~ 3-Core Round",
	"Orange ~ 3-Core Twisted",
	"Pea Green ~ 3-Core Round",
	"Pea Green ~ 3-Core Twisted",
	"Poppy Red ~ 3-Core Round",
	"Poppy Red ~ 3-Core Twisted",
	"Purple ~ 3-Core Round",
	"Purple ~ 3-Core Twisted",
	"Racing Green ~ 3-Core Round",
	"Racing Green ~ 3-Core Twisted",
	"Red & W Herringbone ~ 3-Core Round",
	"Red & W Herringbone ~ 3-Core Twisted",
	"Rose ~ 3-Core Round",
	"Rose ~ 3-Core Twisted",
	"Royal Blue ~ 3-Core Round",
	"Royal Blue ~ 3-Core Twisted",
	"Satinwood Gold ~ 3-Core Round",
	"Satinwood Gold ~ 3-Core Twisted",
	"Silver & White Herringbone ~ 3-Core Round",
	"Silver ~ 3-Core Round",
	"Silver ~ 3-Core Twisted",
	"Tisane ~ 3-Core Round",
	"Tisane ~ 3-Core Twisted",
	"White ~ 3-Core Round",
	"White ~ 3-Core Twisted",
	"Yellow ~ 3-Core Round",
	"Yellow ~ 3-Core Twisted",
	"Incandescent Golfball ~ E14 (SES)",
	"Incandescent Candle ~ E14 (SES)",
	"LED Candle ~ E14 (SES)",
	"LED Golfball ~ E14 (SES)",
	"Halogen Golfball ~ E27 (ES)",
	"LED Golfball ~ E27 (ES)",
	"Incandescent Squirrel ~ E27 (ES)",
	"Incandescent Picture ~ E14 (SES)",
	"Incandescent Golfball ~ E27 (ES)",
	"Incandescent Lantern ~ E27 (ES)",
	"Compact Fluorescent ~ E14 (SES)"
	]
};
